import { Request, Response } from "express";
import { supabaseAdmin } from "../db/supabase";
import { buildMarkdownContent } from "../engine/export";

/**
 * Validates ownership and approval status before sharing operations.
 */
async function validateShareAccess(sessionId: string, userId: string) {
  const { data: session, error } = await supabaseAdmin
    .from("research_sessions")
    .select("*, research_reports(*)")
    .eq("id", sessionId)
    .eq("user_id", userId)
    .single();

  if (error || !session) {
    throw new Error("NOT_FOUND");
  }

  const report = session.research_reports?.[0];
  if (!report || !report.is_approved) {
    throw new Error("NOT_FINALIZED");
  }

  return report;
}

/**
 * GET /api/v1/research/:id/share
 * Returns current share state for owner.
 */
export async function getShareStatus(req: Request, res: Response): Promise<void> {
  try {
    const user = req.user;
    if (!user) {
      res.status(401).json({ success: false, error: { message: "Unauthorized" } });
      return;
    }

    const report = await validateShareAccess(req.params.id, user.id);

    const { data: share } = await supabaseAdmin
      .from("report_shares")
      .select("*")
      .eq("report_id", report.id)
      .single();

    res.status(200).json({ success: true, data: share || null });
  } catch (error: any) {
    if (error.message === "NOT_FOUND") res.status(404).json({ success: false, error: { message: "Session not found" } });
    else if (error.message === "NOT_FINALIZED") res.status(400).json({ success: false, error: { message: "Report not finalized" } });
    else res.status(500).json({ success: false, error: { message: "Internal Error" } });
  }
}

/**
 * POST /api/v1/research/:id/share
 * Creates or updates a share to be active.
 */
export async function enableShare(req: Request, res: Response): Promise<void> {
  try {
    const user = req.user;
    if (!user) {
      res.status(401).json({ success: false, error: { message: "Unauthorized" } });
      return;
    }

    const report = await validateShareAccess(req.params.id, user.id);
    const { expires_at } = req.body || {};

    const { data: share, error } = await supabaseAdmin
      .from("report_shares")
      .upsert({
        report_id: report.id,
        is_public: true,
        expires_at: expires_at || null,
        // share_token is auto-generated by the DB default if not provided during insert
      }, { onConflict: 'report_id' })
      .select()
      .single();

    if (error) throw error;

    res.status(200).json({ success: true, data: share });
  } catch (error: any) {
    if (error.message === "NOT_FOUND") res.status(404).json({ success: false, error: { message: "Session not found" } });
    else if (error.message === "NOT_FINALIZED") res.status(400).json({ success: false, error: { message: "Report not finalized" } });
    else res.status(500).json({ success: false, error: { message: "Internal Error" } });
  }
}

/**
 * DELETE /api/v1/research/:id/share
 * Revokes sharing.
 */
export async function revokeShare(req: Request, res: Response): Promise<void> {
  try {
    const user = req.user;
    if (!user) {
      res.status(401).json({ success: false, error: { message: "Unauthorized" } });
      return;
    }

    const report = await validateShareAccess(req.params.id, user.id);

    const { data: share, error } = await supabaseAdmin
      .from("report_shares")
      .update({ is_public: false })
      .eq("report_id", report.id)
      .select()
      .single();

    res.status(200).json({ success: true, data: share || { revoked: true } });
  } catch (error: any) {
    if (error.message === "NOT_FOUND") res.status(404).json({ success: false, error: { message: "Session not found" } });
    else if (error.message === "NOT_FINALIZED") res.status(400).json({ success: false, error: { message: "Report not finalized" } });
    else res.status(500).json({ success: false, error: { message: "Internal Error" } });
  }
}

/**
 * GET /api/v1/share/:token
 * Unauthenticated public endpoint to fetch the report payload.
 */
export async function getPublicSharedReport(req: Request, res: Response): Promise<void> {
  try {
    const { token } = req.params;
    
    // Lookup share
    const { data: share, error: shareError } = await supabaseAdmin
      .from("report_shares")
      .select("*, report:research_reports(id, title, content, created_at, session_id)")
      .eq("share_token", token)
      .single();

    if (shareError || !share || !share.is_public) {
      res.status(404).json({ success: false, error: { message: "Report not found or not public" } });
      return;
    }

    if (share.expires_at && new Date(share.expires_at) < new Date()) {
      res.status(410).json({ success: false, error: { message: "Share link expired" } });
      return;
    }

    const report = share.report;

    // Fetch citations & evaluations for markdown assembly
    const { data: citations } = await supabaseAdmin
      .from("citations")
      .select("*, source:research_sources(*)")
      .eq("report_id", report.id)
      .order("citation_number", { ascending: true });

    const { data: evalData } = await supabaseAdmin
      .from("research_evaluations")
      .select("*")
      .eq("session_id", report.session_id)
      .single();

    // Generate markdown safely
    const markdown = buildMarkdownContent(report, evalData, citations || []);

    // Increment view count asynchronously
    supabaseAdmin.from("report_shares").update({ view_count: share.view_count + 1 }).eq("id", share.id).then();

    // Strip private internal metadata and return only safe representation
    res.status(200).json({
      success: true,
      data: {
        title: report.title,
        markdown: markdown,
        created_at: share.created_at,
        views: share.view_count + 1
      }
    });
  } catch (error: any) {
    console.error("[ShareController] Public share error:", error);
    res.status(500).json({ success: false, error: { message: "Internal Error" } });
  }
}
